apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h3dzzn-y8-nodejs 
  janus-idp.io/tekton: h3dzzn-y8-nodejs
  backstage.io/kubernetes-id: h3dzzn-y8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h3dzzn-y8-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  